# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08c5f647e27fe2322bf8edd47ee5ccb19f9ac9d59a82624c5c6f9c793d58573d345d6fa0b575e9b5b829b4743b5d78dc706a3795e2689f1200c3e88d075c9736

test:
  secret_key_base: dec843719336768598608ae29de43d4ea437ef8fea5eb1266c44ab847b5bb413c42fae7a31c315f3d72bd71e54b3d961238d191e71b9d5ab5c1e91ac256f22e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
